services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
      - MONGO_INITDB_DATABASE=car_rental

  nats:
    image: nats:latest
    ports:
      - "4222:4222"
      - "8222:8222"
    command: ["--jetstream"]

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  api-gateway:
    build:
      context: .
      dockerfile: api-gateway/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - USER_SERVICE_ADDR=user-service:50051
      - INVENTORY_SERVICE_ADDR=inventory-service:50052
      - BOOKING_SERVICE_ADDR=booking-service:50053
    depends_on:
      - user-service
      - inventory-service
      - booking-service
      - redis

  user-service:
    build:
      context: .
      dockerfile: user-service/Dockerfile
    environment:
      - MONGO_URI=mongodb://mongodb:27017
      - NATS_URL=nats://nats:4222
      - JWT_SECRET=your-secret-key
      - GRPC_PORT=50051
      - REDIS_ADDR=redis:6379
    depends_on:
      - mongodb
      - nats
      - redis
  inventory-service:
    build:
      context: .
      dockerfile: inventory-service/Dockerfile
    environment:
      - MONGO_URI=mongodb://mongodb:27017
      - NATS_URL=nats://nats:4222
      - GRPC_PORT=50052
      - REDIS_ADDR=redis:6379
    depends_on:
      - mongodb
      - nats
      - redis

  booking-service:
    build:
      context: .
      dockerfile: booking-service/Dockerfile
    environment:
      - MONGO_URI=mongodb://mongodb:27017
      - NATS_URL=nats://nats:4222
      - GRPC_PORT=50053
      - REDIS_ADDR=redis:6379
    depends_on:
      - mongodb
      - nats
      - redis
  statistics-service:
    build:
      context: .
      dockerfile: statistics-service/Dockerfile
    environment:
      - MONGO_URI=mongodb://mongodb:27017
      - NATS_URL=nats://nats:4222
      - GRPC_PORT=50056
      - REDIS_ADDR=redis:6379
    depends_on:
      - mongodb
      - nats
      - redis

  nats-service:
    build:
      context: .
      dockerfile: nats-service/Dockerfile
    environment:
      - NATS_URL=nats://nats:4222
    depends_on:
      - nats
      
  email-service:
    build:
      context: .
      dockerfile: email-service/Dockerfile
    environment:
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_USERNAME=studymy56@gmail.com
      - SMTP_PASSWORD=mvzduretzozozcf
      - SMTP_FROM=studymy56@gmail.com
      - NATS_URL=nats://nats:4222
    depends_on:
      - nats

volumes:
  mongodb_data:
