// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.0
// source: statistics/statistics.proto

package statistics

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TimeRange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartDate     string                 `protobuf:"bytes,1,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"` // ISO 8601 format
	EndDate       string                 `protobuf:"bytes,2,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`       // ISO 8601 format
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimeRange) Reset() {
	*x = TimeRange{}
	mi := &file_statistics_statistics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeRange) ProtoMessage() {}

func (x *TimeRange) ProtoReflect() protoreflect.Message {
	mi := &file_statistics_statistics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeRange.ProtoReflect.Descriptor instead.
func (*TimeRange) Descriptor() ([]byte, []int) {
	return file_statistics_statistics_proto_rawDescGZIP(), []int{0}
}

func (x *TimeRange) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *TimeRange) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

type BookingStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TimeRange     *TimeRange             `protobuf:"bytes,1,opt,name=time_range,json=timeRange,proto3" json:"time_range,omitempty"`
	Location      string                 `protobuf:"bytes,2,opt,name=location,proto3" json:"location,omitempty"` // optional
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BookingStatsRequest) Reset() {
	*x = BookingStatsRequest{}
	mi := &file_statistics_statistics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookingStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookingStatsRequest) ProtoMessage() {}

func (x *BookingStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_statistics_statistics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookingStatsRequest.ProtoReflect.Descriptor instead.
func (*BookingStatsRequest) Descriptor() ([]byte, []int) {
	return file_statistics_statistics_proto_rawDescGZIP(), []int{1}
}

func (x *BookingStatsRequest) GetTimeRange() *TimeRange {
	if x != nil {
		return x.TimeRange
	}
	return nil
}

func (x *BookingStatsRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

type BookingStatsResponse struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	TotalBookings         int32                  `protobuf:"varint,1,opt,name=total_bookings,json=totalBookings,proto3" json:"total_bookings,omitempty"`
	ActiveBookings        int32                  `protobuf:"varint,2,opt,name=active_bookings,json=activeBookings,proto3" json:"active_bookings,omitempty"`
	CompletedBookings     int32                  `protobuf:"varint,3,opt,name=completed_bookings,json=completedBookings,proto3" json:"completed_bookings,omitempty"`
	CancelledBookings     int32                  `protobuf:"varint,4,opt,name=cancelled_bookings,json=cancelledBookings,proto3" json:"cancelled_bookings,omitempty"`
	AverageDuration       float64                `protobuf:"fixed64,5,opt,name=average_duration,json=averageDuration,proto3" json:"average_duration,omitempty"`
	BookingsByCarCategory map[string]int32       `protobuf:"bytes,6,rep,name=bookings_by_car_category,json=bookingsByCarCategory,proto3" json:"bookings_by_car_category,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *BookingStatsResponse) Reset() {
	*x = BookingStatsResponse{}
	mi := &file_statistics_statistics_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookingStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookingStatsResponse) ProtoMessage() {}

func (x *BookingStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_statistics_statistics_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookingStatsResponse.ProtoReflect.Descriptor instead.
func (*BookingStatsResponse) Descriptor() ([]byte, []int) {
	return file_statistics_statistics_proto_rawDescGZIP(), []int{2}
}

func (x *BookingStatsResponse) GetTotalBookings() int32 {
	if x != nil {
		return x.TotalBookings
	}
	return 0
}

func (x *BookingStatsResponse) GetActiveBookings() int32 {
	if x != nil {
		return x.ActiveBookings
	}
	return 0
}

func (x *BookingStatsResponse) GetCompletedBookings() int32 {
	if x != nil {
		return x.CompletedBookings
	}
	return 0
}

func (x *BookingStatsResponse) GetCancelledBookings() int32 {
	if x != nil {
		return x.CancelledBookings
	}
	return 0
}

func (x *BookingStatsResponse) GetAverageDuration() float64 {
	if x != nil {
		return x.AverageDuration
	}
	return 0
}

func (x *BookingStatsResponse) GetBookingsByCarCategory() map[string]int32 {
	if x != nil {
		return x.BookingsByCarCategory
	}
	return nil
}

type CarStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TimeRange     *TimeRange             `protobuf:"bytes,1,opt,name=time_range,json=timeRange,proto3" json:"time_range,omitempty"`
	Category      string                 `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"` // optional
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CarStatsRequest) Reset() {
	*x = CarStatsRequest{}
	mi := &file_statistics_statistics_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CarStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CarStatsRequest) ProtoMessage() {}

func (x *CarStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_statistics_statistics_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CarStatsRequest.ProtoReflect.Descriptor instead.
func (*CarStatsRequest) Descriptor() ([]byte, []int) {
	return file_statistics_statistics_proto_rawDescGZIP(), []int{3}
}

func (x *CarStatsRequest) GetTimeRange() *TimeRange {
	if x != nil {
		return x.TimeRange
	}
	return nil
}

func (x *CarStatsRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

type CarStatsResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	TotalCars          int32                  `protobuf:"varint,1,opt,name=total_cars,json=totalCars,proto3" json:"total_cars,omitempty"`
	AvailableCars      int32                  `protobuf:"varint,2,opt,name=available_cars,json=availableCars,proto3" json:"available_cars,omitempty"`
	AverageUtilization float64                `protobuf:"fixed64,3,opt,name=average_utilization,json=averageUtilization,proto3" json:"average_utilization,omitempty"`
	CarsByCategory     map[string]int32       `protobuf:"bytes,4,rep,name=cars_by_category,json=carsByCategory,proto3" json:"cars_by_category,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	MostBookedCars     []*MostBookedCar       `protobuf:"bytes,5,rep,name=most_booked_cars,json=mostBookedCars,proto3" json:"most_booked_cars,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CarStatsResponse) Reset() {
	*x = CarStatsResponse{}
	mi := &file_statistics_statistics_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CarStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CarStatsResponse) ProtoMessage() {}

func (x *CarStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_statistics_statistics_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CarStatsResponse.ProtoReflect.Descriptor instead.
func (*CarStatsResponse) Descriptor() ([]byte, []int) {
	return file_statistics_statistics_proto_rawDescGZIP(), []int{4}
}

func (x *CarStatsResponse) GetTotalCars() int32 {
	if x != nil {
		return x.TotalCars
	}
	return 0
}

func (x *CarStatsResponse) GetAvailableCars() int32 {
	if x != nil {
		return x.AvailableCars
	}
	return 0
}

func (x *CarStatsResponse) GetAverageUtilization() float64 {
	if x != nil {
		return x.AverageUtilization
	}
	return 0
}

func (x *CarStatsResponse) GetCarsByCategory() map[string]int32 {
	if x != nil {
		return x.CarsByCategory
	}
	return nil
}

func (x *CarStatsResponse) GetMostBookedCars() []*MostBookedCar {
	if x != nil {
		return x.MostBookedCars
	}
	return nil
}

type MostBookedCar struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CarId         string                 `protobuf:"bytes,1,opt,name=car_id,json=carId,proto3" json:"car_id,omitempty"`
	Make          string                 `protobuf:"bytes,2,opt,name=make,proto3" json:"make,omitempty"`
	Model         string                 `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	BookingCount  int32                  `protobuf:"varint,4,opt,name=booking_count,json=bookingCount,proto3" json:"booking_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MostBookedCar) Reset() {
	*x = MostBookedCar{}
	mi := &file_statistics_statistics_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MostBookedCar) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MostBookedCar) ProtoMessage() {}

func (x *MostBookedCar) ProtoReflect() protoreflect.Message {
	mi := &file_statistics_statistics_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MostBookedCar.ProtoReflect.Descriptor instead.
func (*MostBookedCar) Descriptor() ([]byte, []int) {
	return file_statistics_statistics_proto_rawDescGZIP(), []int{5}
}

func (x *MostBookedCar) GetCarId() string {
	if x != nil {
		return x.CarId
	}
	return ""
}

func (x *MostBookedCar) GetMake() string {
	if x != nil {
		return x.Make
	}
	return ""
}

func (x *MostBookedCar) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *MostBookedCar) GetBookingCount() int32 {
	if x != nil {
		return x.BookingCount
	}
	return 0
}

type RevenueStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TimeRange     *TimeRange             `protobuf:"bytes,1,opt,name=time_range,json=timeRange,proto3" json:"time_range,omitempty"`
	Location      string                 `protobuf:"bytes,2,opt,name=location,proto3" json:"location,omitempty"` // optional
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevenueStatsRequest) Reset() {
	*x = RevenueStatsRequest{}
	mi := &file_statistics_statistics_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevenueStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevenueStatsRequest) ProtoMessage() {}

func (x *RevenueStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_statistics_statistics_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevenueStatsRequest.ProtoReflect.Descriptor instead.
func (*RevenueStatsRequest) Descriptor() ([]byte, []int) {
	return file_statistics_statistics_proto_rawDescGZIP(), []int{6}
}

func (x *RevenueStatsRequest) GetTimeRange() *TimeRange {
	if x != nil {
		return x.TimeRange
	}
	return nil
}

func (x *RevenueStatsRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

type RevenueStatsResponse struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	TotalRevenue             float64                `protobuf:"fixed64,1,opt,name=total_revenue,json=totalRevenue,proto3" json:"total_revenue,omitempty"`
	AverageRevenuePerBooking float64                `protobuf:"fixed64,2,opt,name=average_revenue_per_booking,json=averageRevenuePerBooking,proto3" json:"average_revenue_per_booking,omitempty"`
	RevenueByCategory        map[string]float64     `protobuf:"bytes,3,rep,name=revenue_by_category,json=revenueByCategory,proto3" json:"revenue_by_category,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	RevenueByLocation        map[string]float64     `protobuf:"bytes,4,rep,name=revenue_by_location,json=revenueByLocation,proto3" json:"revenue_by_location,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	MonthlyRevenue           []*MonthlyRevenue      `protobuf:"bytes,5,rep,name=monthly_revenue,json=monthlyRevenue,proto3" json:"monthly_revenue,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *RevenueStatsResponse) Reset() {
	*x = RevenueStatsResponse{}
	mi := &file_statistics_statistics_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevenueStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevenueStatsResponse) ProtoMessage() {}

func (x *RevenueStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_statistics_statistics_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevenueStatsResponse.ProtoReflect.Descriptor instead.
func (*RevenueStatsResponse) Descriptor() ([]byte, []int) {
	return file_statistics_statistics_proto_rawDescGZIP(), []int{7}
}

func (x *RevenueStatsResponse) GetTotalRevenue() float64 {
	if x != nil {
		return x.TotalRevenue
	}
	return 0
}

func (x *RevenueStatsResponse) GetAverageRevenuePerBooking() float64 {
	if x != nil {
		return x.AverageRevenuePerBooking
	}
	return 0
}

func (x *RevenueStatsResponse) GetRevenueByCategory() map[string]float64 {
	if x != nil {
		return x.RevenueByCategory
	}
	return nil
}

func (x *RevenueStatsResponse) GetRevenueByLocation() map[string]float64 {
	if x != nil {
		return x.RevenueByLocation
	}
	return nil
}

func (x *RevenueStatsResponse) GetMonthlyRevenue() []*MonthlyRevenue {
	if x != nil {
		return x.MonthlyRevenue
	}
	return nil
}

type MonthlyRevenue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Month         string                 `protobuf:"bytes,1,opt,name=month,proto3" json:"month,omitempty"` // YYYY-MM format
	Revenue       float64                `protobuf:"fixed64,2,opt,name=revenue,proto3" json:"revenue,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MonthlyRevenue) Reset() {
	*x = MonthlyRevenue{}
	mi := &file_statistics_statistics_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MonthlyRevenue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonthlyRevenue) ProtoMessage() {}

func (x *MonthlyRevenue) ProtoReflect() protoreflect.Message {
	mi := &file_statistics_statistics_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonthlyRevenue.ProtoReflect.Descriptor instead.
func (*MonthlyRevenue) Descriptor() ([]byte, []int) {
	return file_statistics_statistics_proto_rawDescGZIP(), []int{8}
}

func (x *MonthlyRevenue) GetMonth() string {
	if x != nil {
		return x.Month
	}
	return ""
}

func (x *MonthlyRevenue) GetRevenue() float64 {
	if x != nil {
		return x.Revenue
	}
	return 0
}

type PopularLocationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TimeRange     *TimeRange             `protobuf:"bytes,1,opt,name=time_range,json=timeRange,proto3" json:"time_range,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"` // number of locations to return
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PopularLocationsRequest) Reset() {
	*x = PopularLocationsRequest{}
	mi := &file_statistics_statistics_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PopularLocationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PopularLocationsRequest) ProtoMessage() {}

func (x *PopularLocationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_statistics_statistics_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PopularLocationsRequest.ProtoReflect.Descriptor instead.
func (*PopularLocationsRequest) Descriptor() ([]byte, []int) {
	return file_statistics_statistics_proto_rawDescGZIP(), []int{9}
}

func (x *PopularLocationsRequest) GetTimeRange() *TimeRange {
	if x != nil {
		return x.TimeRange
	}
	return nil
}

func (x *PopularLocationsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type PopularLocationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Locations     []*LocationStats       `protobuf:"bytes,1,rep,name=locations,proto3" json:"locations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PopularLocationsResponse) Reset() {
	*x = PopularLocationsResponse{}
	mi := &file_statistics_statistics_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PopularLocationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PopularLocationsResponse) ProtoMessage() {}

func (x *PopularLocationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_statistics_statistics_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PopularLocationsResponse.ProtoReflect.Descriptor instead.
func (*PopularLocationsResponse) Descriptor() ([]byte, []int) {
	return file_statistics_statistics_proto_rawDescGZIP(), []int{10}
}

func (x *PopularLocationsResponse) GetLocations() []*LocationStats {
	if x != nil {
		return x.Locations
	}
	return nil
}

type LocationStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Location      string                 `protobuf:"bytes,1,opt,name=location,proto3" json:"location,omitempty"`
	BookingCount  int32                  `protobuf:"varint,2,opt,name=booking_count,json=bookingCount,proto3" json:"booking_count,omitempty"`
	Revenue       float64                `protobuf:"fixed64,3,opt,name=revenue,proto3" json:"revenue,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocationStats) Reset() {
	*x = LocationStats{}
	mi := &file_statistics_statistics_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocationStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocationStats) ProtoMessage() {}

func (x *LocationStats) ProtoReflect() protoreflect.Message {
	mi := &file_statistics_statistics_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocationStats.ProtoReflect.Descriptor instead.
func (*LocationStats) Descriptor() ([]byte, []int) {
	return file_statistics_statistics_proto_rawDescGZIP(), []int{11}
}

func (x *LocationStats) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *LocationStats) GetBookingCount() int32 {
	if x != nil {
		return x.BookingCount
	}
	return 0
}

func (x *LocationStats) GetRevenue() float64 {
	if x != nil {
		return x.Revenue
	}
	return 0
}

type UserStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TimeRange     *TimeRange             `protobuf:"bytes,1,opt,name=time_range,json=timeRange,proto3" json:"time_range,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserStatsRequest) Reset() {
	*x = UserStatsRequest{}
	mi := &file_statistics_statistics_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserStatsRequest) ProtoMessage() {}

func (x *UserStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_statistics_statistics_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserStatsRequest.ProtoReflect.Descriptor instead.
func (*UserStatsRequest) Descriptor() ([]byte, []int) {
	return file_statistics_statistics_proto_rawDescGZIP(), []int{12}
}

func (x *UserStatsRequest) GetTimeRange() *TimeRange {
	if x != nil {
		return x.TimeRange
	}
	return nil
}

type UserStatsResponse struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	TotalUsers             int32                  `protobuf:"varint,1,opt,name=total_users,json=totalUsers,proto3" json:"total_users,omitempty"`
	ActiveUsers            int32                  `protobuf:"varint,2,opt,name=active_users,json=activeUsers,proto3" json:"active_users,omitempty"`
	AverageBookingsPerUser float64                `protobuf:"fixed64,3,opt,name=average_bookings_per_user,json=averageBookingsPerUser,proto3" json:"average_bookings_per_user,omitempty"`
	TopUsers               []*TopUser             `protobuf:"bytes,4,rep,name=top_users,json=topUsers,proto3" json:"top_users,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *UserStatsResponse) Reset() {
	*x = UserStatsResponse{}
	mi := &file_statistics_statistics_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserStatsResponse) ProtoMessage() {}

func (x *UserStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_statistics_statistics_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserStatsResponse.ProtoReflect.Descriptor instead.
func (*UserStatsResponse) Descriptor() ([]byte, []int) {
	return file_statistics_statistics_proto_rawDescGZIP(), []int{13}
}

func (x *UserStatsResponse) GetTotalUsers() int32 {
	if x != nil {
		return x.TotalUsers
	}
	return 0
}

func (x *UserStatsResponse) GetActiveUsers() int32 {
	if x != nil {
		return x.ActiveUsers
	}
	return 0
}

func (x *UserStatsResponse) GetAverageBookingsPerUser() float64 {
	if x != nil {
		return x.AverageBookingsPerUser
	}
	return 0
}

func (x *UserStatsResponse) GetTopUsers() []*TopUser {
	if x != nil {
		return x.TopUsers
	}
	return nil
}

type TopUser struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	BookingCount  int32                  `protobuf:"varint,2,opt,name=booking_count,json=bookingCount,proto3" json:"booking_count,omitempty"`
	TotalSpent    float64                `protobuf:"fixed64,3,opt,name=total_spent,json=totalSpent,proto3" json:"total_spent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopUser) Reset() {
	*x = TopUser{}
	mi := &file_statistics_statistics_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopUser) ProtoMessage() {}

func (x *TopUser) ProtoReflect() protoreflect.Message {
	mi := &file_statistics_statistics_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopUser.ProtoReflect.Descriptor instead.
func (*TopUser) Descriptor() ([]byte, []int) {
	return file_statistics_statistics_proto_rawDescGZIP(), []int{14}
}

func (x *TopUser) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *TopUser) GetBookingCount() int32 {
	if x != nil {
		return x.BookingCount
	}
	return 0
}

func (x *TopUser) GetTotalSpent() float64 {
	if x != nil {
		return x.TotalSpent
	}
	return 0
}

var File_statistics_statistics_proto protoreflect.FileDescriptor

const file_statistics_statistics_proto_rawDesc = "" +
	"\n" +
	"\x1bstatistics/statistics.proto\x12\x1ecarrental.com.proto.statistics\"E\n" +
	"\tTimeRange\x12\x1d\n" +
	"\n" +
	"start_date\x18\x01 \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\x02 \x01(\tR\aendDate\"{\n" +
	"\x13BookingStatsRequest\x12H\n" +
	"\n" +
	"time_range\x18\x01 \x01(\v2).carrental.com.proto.statistics.TimeRangeR\ttimeRange\x12\x1a\n" +
	"\blocation\x18\x02 \x01(\tR\blocation\"\xc4\x03\n" +
	"\x14BookingStatsResponse\x12%\n" +
	"\x0etotal_bookings\x18\x01 \x01(\x05R\rtotalBookings\x12'\n" +
	"\x0factive_bookings\x18\x02 \x01(\x05R\x0eactiveBookings\x12-\n" +
	"\x12completed_bookings\x18\x03 \x01(\x05R\x11completedBookings\x12-\n" +
	"\x12cancelled_bookings\x18\x04 \x01(\x05R\x11cancelledBookings\x12)\n" +
	"\x10average_duration\x18\x05 \x01(\x01R\x0faverageDuration\x12\x88\x01\n" +
	"\x18bookings_by_car_category\x18\x06 \x03(\v2O.carrental.com.proto.statistics.BookingStatsResponse.BookingsByCarCategoryEntryR\x15bookingsByCarCategory\x1aH\n" +
	"\x1aBookingsByCarCategoryEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"w\n" +
	"\x0fCarStatsRequest\x12H\n" +
	"\n" +
	"time_range\x18\x01 \x01(\v2).carrental.com.proto.statistics.TimeRangeR\ttimeRange\x12\x1a\n" +
	"\bcategory\x18\x02 \x01(\tR\bcategory\"\x95\x03\n" +
	"\x10CarStatsResponse\x12\x1d\n" +
	"\n" +
	"total_cars\x18\x01 \x01(\x05R\ttotalCars\x12%\n" +
	"\x0eavailable_cars\x18\x02 \x01(\x05R\ravailableCars\x12/\n" +
	"\x13average_utilization\x18\x03 \x01(\x01R\x12averageUtilization\x12n\n" +
	"\x10cars_by_category\x18\x04 \x03(\v2D.carrental.com.proto.statistics.CarStatsResponse.CarsByCategoryEntryR\x0ecarsByCategory\x12W\n" +
	"\x10most_booked_cars\x18\x05 \x03(\v2-.carrental.com.proto.statistics.MostBookedCarR\x0emostBookedCars\x1aA\n" +
	"\x13CarsByCategoryEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"u\n" +
	"\rMostBookedCar\x12\x15\n" +
	"\x06car_id\x18\x01 \x01(\tR\x05carId\x12\x12\n" +
	"\x04make\x18\x02 \x01(\tR\x04make\x12\x14\n" +
	"\x05model\x18\x03 \x01(\tR\x05model\x12#\n" +
	"\rbooking_count\x18\x04 \x01(\x05R\fbookingCount\"{\n" +
	"\x13RevenueStatsRequest\x12H\n" +
	"\n" +
	"time_range\x18\x01 \x01(\v2).carrental.com.proto.statistics.TimeRangeR\ttimeRange\x12\x1a\n" +
	"\blocation\x18\x02 \x01(\tR\blocation\"\xd9\x04\n" +
	"\x14RevenueStatsResponse\x12#\n" +
	"\rtotal_revenue\x18\x01 \x01(\x01R\ftotalRevenue\x12=\n" +
	"\x1baverage_revenue_per_booking\x18\x02 \x01(\x01R\x18averageRevenuePerBooking\x12{\n" +
	"\x13revenue_by_category\x18\x03 \x03(\v2K.carrental.com.proto.statistics.RevenueStatsResponse.RevenueByCategoryEntryR\x11revenueByCategory\x12{\n" +
	"\x13revenue_by_location\x18\x04 \x03(\v2K.carrental.com.proto.statistics.RevenueStatsResponse.RevenueByLocationEntryR\x11revenueByLocation\x12W\n" +
	"\x0fmonthly_revenue\x18\x05 \x03(\v2..carrental.com.proto.statistics.MonthlyRevenueR\x0emonthlyRevenue\x1aD\n" +
	"\x16RevenueByCategoryEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\x1aD\n" +
	"\x16RevenueByLocationEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\"@\n" +
	"\x0eMonthlyRevenue\x12\x14\n" +
	"\x05month\x18\x01 \x01(\tR\x05month\x12\x18\n" +
	"\arevenue\x18\x02 \x01(\x01R\arevenue\"y\n" +
	"\x17PopularLocationsRequest\x12H\n" +
	"\n" +
	"time_range\x18\x01 \x01(\v2).carrental.com.proto.statistics.TimeRangeR\ttimeRange\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"g\n" +
	"\x18PopularLocationsResponse\x12K\n" +
	"\tlocations\x18\x01 \x03(\v2-.carrental.com.proto.statistics.LocationStatsR\tlocations\"j\n" +
	"\rLocationStats\x12\x1a\n" +
	"\blocation\x18\x01 \x01(\tR\blocation\x12#\n" +
	"\rbooking_count\x18\x02 \x01(\x05R\fbookingCount\x12\x18\n" +
	"\arevenue\x18\x03 \x01(\x01R\arevenue\"\\\n" +
	"\x10UserStatsRequest\x12H\n" +
	"\n" +
	"time_range\x18\x01 \x01(\v2).carrental.com.proto.statistics.TimeRangeR\ttimeRange\"\xd8\x01\n" +
	"\x11UserStatsResponse\x12\x1f\n" +
	"\vtotal_users\x18\x01 \x01(\x05R\n" +
	"totalUsers\x12!\n" +
	"\factive_users\x18\x02 \x01(\x05R\vactiveUsers\x129\n" +
	"\x19average_bookings_per_user\x18\x03 \x01(\x01R\x16averageBookingsPerUser\x12D\n" +
	"\ttop_users\x18\x04 \x03(\v2'.carrental.com.proto.statistics.TopUserR\btopUsers\"h\n" +
	"\aTopUser\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12#\n" +
	"\rbooking_count\x18\x02 \x01(\x05R\fbookingCount\x12\x1f\n" +
	"\vtotal_spent\x18\x03 \x01(\x01R\n" +
	"totalSpent2\x81\x05\n" +
	"\x11StatisticsService\x12|\n" +
	"\x0fGetBookingStats\x123.carrental.com.proto.statistics.BookingStatsRequest\x1a4.carrental.com.proto.statistics.BookingStatsResponse\x12p\n" +
	"\vGetCarStats\x12/.carrental.com.proto.statistics.CarStatsRequest\x1a0.carrental.com.proto.statistics.CarStatsResponse\x12|\n" +
	"\x0fGetRevenueStats\x123.carrental.com.proto.statistics.RevenueStatsRequest\x1a4.carrental.com.proto.statistics.RevenueStatsResponse\x12\x88\x01\n" +
	"\x13GetPopularLocations\x127.carrental.com.proto.statistics.PopularLocationsRequest\x1a8.carrental.com.proto.statistics.PopularLocationsResponse\x12s\n" +
	"\fGetUserStats\x120.carrental.com.proto.statistics.UserStatsRequest\x1a1.carrental.com.proto.statistics.UserStatsResponseB Z\x1ecarrental.com/proto/statisticsb\x06proto3"

var (
	file_statistics_statistics_proto_rawDescOnce sync.Once
	file_statistics_statistics_proto_rawDescData []byte
)

func file_statistics_statistics_proto_rawDescGZIP() []byte {
	file_statistics_statistics_proto_rawDescOnce.Do(func() {
		file_statistics_statistics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_statistics_statistics_proto_rawDesc), len(file_statistics_statistics_proto_rawDesc)))
	})
	return file_statistics_statistics_proto_rawDescData
}

var file_statistics_statistics_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_statistics_statistics_proto_goTypes = []any{
	(*TimeRange)(nil),                // 0: carrental.com.proto.statistics.TimeRange
	(*BookingStatsRequest)(nil),      // 1: carrental.com.proto.statistics.BookingStatsRequest
	(*BookingStatsResponse)(nil),     // 2: carrental.com.proto.statistics.BookingStatsResponse
	(*CarStatsRequest)(nil),          // 3: carrental.com.proto.statistics.CarStatsRequest
	(*CarStatsResponse)(nil),         // 4: carrental.com.proto.statistics.CarStatsResponse
	(*MostBookedCar)(nil),            // 5: carrental.com.proto.statistics.MostBookedCar
	(*RevenueStatsRequest)(nil),      // 6: carrental.com.proto.statistics.RevenueStatsRequest
	(*RevenueStatsResponse)(nil),     // 7: carrental.com.proto.statistics.RevenueStatsResponse
	(*MonthlyRevenue)(nil),           // 8: carrental.com.proto.statistics.MonthlyRevenue
	(*PopularLocationsRequest)(nil),  // 9: carrental.com.proto.statistics.PopularLocationsRequest
	(*PopularLocationsResponse)(nil), // 10: carrental.com.proto.statistics.PopularLocationsResponse
	(*LocationStats)(nil),            // 11: carrental.com.proto.statistics.LocationStats
	(*UserStatsRequest)(nil),         // 12: carrental.com.proto.statistics.UserStatsRequest
	(*UserStatsResponse)(nil),        // 13: carrental.com.proto.statistics.UserStatsResponse
	(*TopUser)(nil),                  // 14: carrental.com.proto.statistics.TopUser
	nil,                              // 15: carrental.com.proto.statistics.BookingStatsResponse.BookingsByCarCategoryEntry
	nil,                              // 16: carrental.com.proto.statistics.CarStatsResponse.CarsByCategoryEntry
	nil,                              // 17: carrental.com.proto.statistics.RevenueStatsResponse.RevenueByCategoryEntry
	nil,                              // 18: carrental.com.proto.statistics.RevenueStatsResponse.RevenueByLocationEntry
}
var file_statistics_statistics_proto_depIdxs = []int32{
	0,  // 0: carrental.com.proto.statistics.BookingStatsRequest.time_range:type_name -> carrental.com.proto.statistics.TimeRange
	15, // 1: carrental.com.proto.statistics.BookingStatsResponse.bookings_by_car_category:type_name -> carrental.com.proto.statistics.BookingStatsResponse.BookingsByCarCategoryEntry
	0,  // 2: carrental.com.proto.statistics.CarStatsRequest.time_range:type_name -> carrental.com.proto.statistics.TimeRange
	16, // 3: carrental.com.proto.statistics.CarStatsResponse.cars_by_category:type_name -> carrental.com.proto.statistics.CarStatsResponse.CarsByCategoryEntry
	5,  // 4: carrental.com.proto.statistics.CarStatsResponse.most_booked_cars:type_name -> carrental.com.proto.statistics.MostBookedCar
	0,  // 5: carrental.com.proto.statistics.RevenueStatsRequest.time_range:type_name -> carrental.com.proto.statistics.TimeRange
	17, // 6: carrental.com.proto.statistics.RevenueStatsResponse.revenue_by_category:type_name -> carrental.com.proto.statistics.RevenueStatsResponse.RevenueByCategoryEntry
	18, // 7: carrental.com.proto.statistics.RevenueStatsResponse.revenue_by_location:type_name -> carrental.com.proto.statistics.RevenueStatsResponse.RevenueByLocationEntry
	8,  // 8: carrental.com.proto.statistics.RevenueStatsResponse.monthly_revenue:type_name -> carrental.com.proto.statistics.MonthlyRevenue
	0,  // 9: carrental.com.proto.statistics.PopularLocationsRequest.time_range:type_name -> carrental.com.proto.statistics.TimeRange
	11, // 10: carrental.com.proto.statistics.PopularLocationsResponse.locations:type_name -> carrental.com.proto.statistics.LocationStats
	0,  // 11: carrental.com.proto.statistics.UserStatsRequest.time_range:type_name -> carrental.com.proto.statistics.TimeRange
	14, // 12: carrental.com.proto.statistics.UserStatsResponse.top_users:type_name -> carrental.com.proto.statistics.TopUser
	1,  // 13: carrental.com.proto.statistics.StatisticsService.GetBookingStats:input_type -> carrental.com.proto.statistics.BookingStatsRequest
	3,  // 14: carrental.com.proto.statistics.StatisticsService.GetCarStats:input_type -> carrental.com.proto.statistics.CarStatsRequest
	6,  // 15: carrental.com.proto.statistics.StatisticsService.GetRevenueStats:input_type -> carrental.com.proto.statistics.RevenueStatsRequest
	9,  // 16: carrental.com.proto.statistics.StatisticsService.GetPopularLocations:input_type -> carrental.com.proto.statistics.PopularLocationsRequest
	12, // 17: carrental.com.proto.statistics.StatisticsService.GetUserStats:input_type -> carrental.com.proto.statistics.UserStatsRequest
	2,  // 18: carrental.com.proto.statistics.StatisticsService.GetBookingStats:output_type -> carrental.com.proto.statistics.BookingStatsResponse
	4,  // 19: carrental.com.proto.statistics.StatisticsService.GetCarStats:output_type -> carrental.com.proto.statistics.CarStatsResponse
	7,  // 20: carrental.com.proto.statistics.StatisticsService.GetRevenueStats:output_type -> carrental.com.proto.statistics.RevenueStatsResponse
	10, // 21: carrental.com.proto.statistics.StatisticsService.GetPopularLocations:output_type -> carrental.com.proto.statistics.PopularLocationsResponse
	13, // 22: carrental.com.proto.statistics.StatisticsService.GetUserStats:output_type -> carrental.com.proto.statistics.UserStatsResponse
	18, // [18:23] is the sub-list for method output_type
	13, // [13:18] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_statistics_statistics_proto_init() }
func file_statistics_statistics_proto_init() {
	if File_statistics_statistics_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_statistics_statistics_proto_rawDesc), len(file_statistics_statistics_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_statistics_statistics_proto_goTypes,
		DependencyIndexes: file_statistics_statistics_proto_depIdxs,
		MessageInfos:      file_statistics_statistics_proto_msgTypes,
	}.Build()
	File_statistics_statistics_proto = out.File
	file_statistics_statistics_proto_goTypes = nil
	file_statistics_statistics_proto_depIdxs = nil
}
