// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.0
// source: inventory/inventory.proto

package inventory

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Category      string                 `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"`
	Stock         int32                  `protobuf:"varint,3,opt,name=stock,proto3" json:"stock,omitempty"`
	Price         float64                `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProductRequest) Reset() {
	*x = CreateProductRequest{}
	mi := &file_inventory_inventory_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProductRequest) ProtoMessage() {}

func (x *CreateProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_inventory_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProductRequest.ProtoReflect.Descriptor instead.
func (*CreateProductRequest) Descriptor() ([]byte, []int) {
	return file_inventory_inventory_proto_rawDescGZIP(), []int{0}
}

func (x *CreateProductRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateProductRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *CreateProductRequest) GetStock() int32 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *CreateProductRequest) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

type GetProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductRequest) Reset() {
	*x = GetProductRequest{}
	mi := &file_inventory_inventory_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductRequest) ProtoMessage() {}

func (x *GetProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_inventory_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductRequest.ProtoReflect.Descriptor instead.
func (*GetProductRequest) Descriptor() ([]byte, []int) {
	return file_inventory_inventory_proto_rawDescGZIP(), []int{1}
}

func (x *GetProductRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type UpdateProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Category      string                 `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	Stock         int32                  `protobuf:"varint,4,opt,name=stock,proto3" json:"stock,omitempty"`
	Price         float64                `protobuf:"fixed64,5,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProductRequest) Reset() {
	*x = UpdateProductRequest{}
	mi := &file_inventory_inventory_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProductRequest) ProtoMessage() {}

func (x *UpdateProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_inventory_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProductRequest.ProtoReflect.Descriptor instead.
func (*UpdateProductRequest) Descriptor() ([]byte, []int) {
	return file_inventory_inventory_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateProductRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateProductRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateProductRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *UpdateProductRequest) GetStock() int32 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *UpdateProductRequest) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

type DeleteProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProductRequest) Reset() {
	*x = DeleteProductRequest{}
	mi := &file_inventory_inventory_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProductRequest) ProtoMessage() {}

func (x *DeleteProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_inventory_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProductRequest.ProtoReflect.Descriptor instead.
func (*DeleteProductRequest) Descriptor() ([]byte, []int) {
	return file_inventory_inventory_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteProductRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ListProductsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProductsRequest) Reset() {
	*x = ListProductsRequest{}
	mi := &file_inventory_inventory_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProductsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProductsRequest) ProtoMessage() {}

func (x *ListProductsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_inventory_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProductsRequest.ProtoReflect.Descriptor instead.
func (*ListProductsRequest) Descriptor() ([]byte, []int) {
	return file_inventory_inventory_proto_rawDescGZIP(), []int{4}
}

type AdjustStockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     int32                  `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Delta         int32                  `protobuf:"varint,2,opt,name=delta,proto3" json:"delta,omitempty"` // can be negative (to reduce stock) or positive (to increase)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdjustStockRequest) Reset() {
	*x = AdjustStockRequest{}
	mi := &file_inventory_inventory_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdjustStockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdjustStockRequest) ProtoMessage() {}

func (x *AdjustStockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_inventory_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdjustStockRequest.ProtoReflect.Descriptor instead.
func (*AdjustStockRequest) Descriptor() ([]byte, []int) {
	return file_inventory_inventory_proto_rawDescGZIP(), []int{5}
}

func (x *AdjustStockRequest) GetProductId() int32 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *AdjustStockRequest) GetDelta() int32 {
	if x != nil {
		return x.Delta
	}
	return 0
}

type ProductResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Category      string                 `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	Stock         int32                  `protobuf:"varint,4,opt,name=stock,proto3" json:"stock,omitempty"`
	Price         float64                `protobuf:"fixed64,5,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductResponse) Reset() {
	*x = ProductResponse{}
	mi := &file_inventory_inventory_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductResponse) ProtoMessage() {}

func (x *ProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_inventory_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductResponse.ProtoReflect.Descriptor instead.
func (*ProductResponse) Descriptor() ([]byte, []int) {
	return file_inventory_inventory_proto_rawDescGZIP(), []int{6}
}

func (x *ProductResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ProductResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProductResponse) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *ProductResponse) GetStock() int32 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *ProductResponse) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

type ListProductsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Products      []*ProductResponse     `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProductsResponse) Reset() {
	*x = ListProductsResponse{}
	mi := &file_inventory_inventory_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProductsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProductsResponse) ProtoMessage() {}

func (x *ListProductsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_inventory_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProductsResponse.ProtoReflect.Descriptor instead.
func (*ListProductsResponse) Descriptor() ([]byte, []int) {
	return file_inventory_inventory_proto_rawDescGZIP(), []int{7}
}

func (x *ListProductsResponse) GetProducts() []*ProductResponse {
	if x != nil {
		return x.Products
	}
	return nil
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_inventory_inventory_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_inventory_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_inventory_inventory_proto_rawDescGZIP(), []int{8}
}

type AddCarRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Make          string                 `protobuf:"bytes,1,opt,name=make,proto3" json:"make,omitempty"`
	Model         string                 `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	Year          int32                  `protobuf:"varint,3,opt,name=year,proto3" json:"year,omitempty"`
	Category      string                 `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`
	PricePerDay   float64                `protobuf:"fixed64,5,opt,name=price_per_day,json=pricePerDay,proto3" json:"price_per_day,omitempty"`
	Location      string                 `protobuf:"bytes,6,opt,name=location,proto3" json:"location,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddCarRequest) Reset() {
	*x = AddCarRequest{}
	mi := &file_inventory_inventory_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddCarRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddCarRequest) ProtoMessage() {}

func (x *AddCarRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_inventory_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddCarRequest.ProtoReflect.Descriptor instead.
func (*AddCarRequest) Descriptor() ([]byte, []int) {
	return file_inventory_inventory_proto_rawDescGZIP(), []int{9}
}

func (x *AddCarRequest) GetMake() string {
	if x != nil {
		return x.Make
	}
	return ""
}

func (x *AddCarRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *AddCarRequest) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *AddCarRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *AddCarRequest) GetPricePerDay() float64 {
	if x != nil {
		return x.PricePerDay
	}
	return 0
}

func (x *AddCarRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

type UpdateCarRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CarId         string                 `protobuf:"bytes,1,opt,name=car_id,json=carId,proto3" json:"car_id,omitempty"`
	Make          string                 `protobuf:"bytes,2,opt,name=make,proto3" json:"make,omitempty"`
	Model         string                 `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	Year          int32                  `protobuf:"varint,4,opt,name=year,proto3" json:"year,omitempty"`
	Category      string                 `protobuf:"bytes,5,opt,name=category,proto3" json:"category,omitempty"`
	PricePerDay   float64                `protobuf:"fixed64,6,opt,name=price_per_day,json=pricePerDay,proto3" json:"price_per_day,omitempty"`
	Location      string                 `protobuf:"bytes,7,opt,name=location,proto3" json:"location,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCarRequest) Reset() {
	*x = UpdateCarRequest{}
	mi := &file_inventory_inventory_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCarRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCarRequest) ProtoMessage() {}

func (x *UpdateCarRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_inventory_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCarRequest.ProtoReflect.Descriptor instead.
func (*UpdateCarRequest) Descriptor() ([]byte, []int) {
	return file_inventory_inventory_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateCarRequest) GetCarId() string {
	if x != nil {
		return x.CarId
	}
	return ""
}

func (x *UpdateCarRequest) GetMake() string {
	if x != nil {
		return x.Make
	}
	return ""
}

func (x *UpdateCarRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *UpdateCarRequest) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *UpdateCarRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *UpdateCarRequest) GetPricePerDay() float64 {
	if x != nil {
		return x.PricePerDay
	}
	return 0
}

func (x *UpdateCarRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

type CarIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CarId         string                 `protobuf:"bytes,1,opt,name=car_id,json=carId,proto3" json:"car_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CarIDRequest) Reset() {
	*x = CarIDRequest{}
	mi := &file_inventory_inventory_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CarIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CarIDRequest) ProtoMessage() {}

func (x *CarIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_inventory_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CarIDRequest.ProtoReflect.Descriptor instead.
func (*CarIDRequest) Descriptor() ([]byte, []int) {
	return file_inventory_inventory_proto_rawDescGZIP(), []int{11}
}

func (x *CarIDRequest) GetCarId() string {
	if x != nil {
		return x.CarId
	}
	return ""
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_inventory_inventory_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_inventory_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_inventory_inventory_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type CarResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CarId         string                 `protobuf:"bytes,1,opt,name=car_id,json=carId,proto3" json:"car_id,omitempty"`
	Make          string                 `protobuf:"bytes,2,opt,name=make,proto3" json:"make,omitempty"`
	Model         string                 `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	Year          int32                  `protobuf:"varint,4,opt,name=year,proto3" json:"year,omitempty"`
	Category      string                 `protobuf:"bytes,5,opt,name=category,proto3" json:"category,omitempty"`
	PricePerDay   float64                `protobuf:"fixed64,6,opt,name=price_per_day,json=pricePerDay,proto3" json:"price_per_day,omitempty"`
	Location      string                 `protobuf:"bytes,7,opt,name=location,proto3" json:"location,omitempty"`
	Available     bool                   `protobuf:"varint,8,opt,name=available,proto3" json:"available,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CarResponse) Reset() {
	*x = CarResponse{}
	mi := &file_inventory_inventory_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CarResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CarResponse) ProtoMessage() {}

func (x *CarResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_inventory_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CarResponse.ProtoReflect.Descriptor instead.
func (*CarResponse) Descriptor() ([]byte, []int) {
	return file_inventory_inventory_proto_rawDescGZIP(), []int{13}
}

func (x *CarResponse) GetCarId() string {
	if x != nil {
		return x.CarId
	}
	return ""
}

func (x *CarResponse) GetMake() string {
	if x != nil {
		return x.Make
	}
	return ""
}

func (x *CarResponse) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *CarResponse) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *CarResponse) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *CarResponse) GetPricePerDay() float64 {
	if x != nil {
		return x.PricePerDay
	}
	return 0
}

func (x *CarResponse) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *CarResponse) GetAvailable() bool {
	if x != nil {
		return x.Available
	}
	return false
}

type SearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Location      string                 `protobuf:"bytes,1,opt,name=location,proto3" json:"location,omitempty"`
	Category      string                 `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"`
	Make          string                 `protobuf:"bytes,3,opt,name=make,proto3" json:"make,omitempty"`
	Model         string                 `protobuf:"bytes,4,opt,name=model,proto3" json:"model,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_inventory_inventory_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_inventory_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_inventory_inventory_proto_rawDescGZIP(), []int{14}
}

func (x *SearchRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *SearchRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *SearchRequest) GetMake() string {
	if x != nil {
		return x.Make
	}
	return ""
}

func (x *SearchRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

type CarListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cars          []*CarResponse         `protobuf:"bytes,1,rep,name=cars,proto3" json:"cars,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CarListResponse) Reset() {
	*x = CarListResponse{}
	mi := &file_inventory_inventory_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CarListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CarListResponse) ProtoMessage() {}

func (x *CarListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_inventory_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CarListResponse.ProtoReflect.Descriptor instead.
func (*CarListResponse) Descriptor() ([]byte, []int) {
	return file_inventory_inventory_proto_rawDescGZIP(), []int{15}
}

func (x *CarListResponse) GetCars() []*CarResponse {
	if x != nil {
		return x.Cars
	}
	return nil
}

type AvailabilityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CarId         string                 `protobuf:"bytes,1,opt,name=car_id,json=carId,proto3" json:"car_id,omitempty"`
	StartDate     string                 `protobuf:"bytes,2,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       string                 `protobuf:"bytes,3,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AvailabilityRequest) Reset() {
	*x = AvailabilityRequest{}
	mi := &file_inventory_inventory_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AvailabilityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AvailabilityRequest) ProtoMessage() {}

func (x *AvailabilityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_inventory_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AvailabilityRequest.ProtoReflect.Descriptor instead.
func (*AvailabilityRequest) Descriptor() ([]byte, []int) {
	return file_inventory_inventory_proto_rawDescGZIP(), []int{16}
}

func (x *AvailabilityRequest) GetCarId() string {
	if x != nil {
		return x.CarId
	}
	return ""
}

func (x *AvailabilityRequest) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *AvailabilityRequest) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

type AvailabilityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Available     bool                   `protobuf:"varint,1,opt,name=available,proto3" json:"available,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AvailabilityResponse) Reset() {
	*x = AvailabilityResponse{}
	mi := &file_inventory_inventory_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AvailabilityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AvailabilityResponse) ProtoMessage() {}

func (x *AvailabilityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_inventory_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AvailabilityResponse.ProtoReflect.Descriptor instead.
func (*AvailabilityResponse) Descriptor() ([]byte, []int) {
	return file_inventory_inventory_proto_rawDescGZIP(), []int{17}
}

func (x *AvailabilityResponse) GetAvailable() bool {
	if x != nil {
		return x.Available
	}
	return false
}

type CarStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CarId         string                 `protobuf:"bytes,1,opt,name=car_id,json=carId,proto3" json:"car_id,omitempty"`
	Available     bool                   `protobuf:"varint,2,opt,name=available,proto3" json:"available,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CarStatusRequest) Reset() {
	*x = CarStatusRequest{}
	mi := &file_inventory_inventory_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CarStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CarStatusRequest) ProtoMessage() {}

func (x *CarStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_inventory_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CarStatusRequest.ProtoReflect.Descriptor instead.
func (*CarStatusRequest) Descriptor() ([]byte, []int) {
	return file_inventory_inventory_proto_rawDescGZIP(), []int{18}
}

func (x *CarStatusRequest) GetCarId() string {
	if x != nil {
		return x.CarId
	}
	return ""
}

func (x *CarStatusRequest) GetAvailable() bool {
	if x != nil {
		return x.Available
	}
	return false
}

type CarIDListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CarIds        []string               `protobuf:"bytes,1,rep,name=car_ids,json=carIds,proto3" json:"car_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CarIDListRequest) Reset() {
	*x = CarIDListRequest{}
	mi := &file_inventory_inventory_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CarIDListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CarIDListRequest) ProtoMessage() {}

func (x *CarIDListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_inventory_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CarIDListRequest.ProtoReflect.Descriptor instead.
func (*CarIDListRequest) Descriptor() ([]byte, []int) {
	return file_inventory_inventory_proto_rawDescGZIP(), []int{19}
}

func (x *CarIDListRequest) GetCarIds() []string {
	if x != nil {
		return x.CarIds
	}
	return nil
}

var File_inventory_inventory_proto protoreflect.FileDescriptor

const file_inventory_inventory_proto_rawDesc = "" +
	"\n" +
	"\x19inventory/inventory.proto\x12\x1dcarrental.com.proto.inventory\"r\n" +
	"\x14CreateProductRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\bcategory\x18\x02 \x01(\tR\bcategory\x12\x14\n" +
	"\x05stock\x18\x03 \x01(\x05R\x05stock\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x01R\x05price\"#\n" +
	"\x11GetProductRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"\x82\x01\n" +
	"\x14UpdateProductRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bcategory\x18\x03 \x01(\tR\bcategory\x12\x14\n" +
	"\x05stock\x18\x04 \x01(\x05R\x05stock\x12\x14\n" +
	"\x05price\x18\x05 \x01(\x01R\x05price\"&\n" +
	"\x14DeleteProductRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"\x15\n" +
	"\x13ListProductsRequest\"I\n" +
	"\x12AdjustStockRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x05R\tproductId\x12\x14\n" +
	"\x05delta\x18\x02 \x01(\x05R\x05delta\"}\n" +
	"\x0fProductResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bcategory\x18\x03 \x01(\tR\bcategory\x12\x14\n" +
	"\x05stock\x18\x04 \x01(\x05R\x05stock\x12\x14\n" +
	"\x05price\x18\x05 \x01(\x01R\x05price\"b\n" +
	"\x14ListProductsResponse\x12J\n" +
	"\bproducts\x18\x01 \x03(\v2..carrental.com.proto.inventory.ProductResponseR\bproducts\"\a\n" +
	"\x05Empty\"\xa9\x01\n" +
	"\rAddCarRequest\x12\x12\n" +
	"\x04make\x18\x01 \x01(\tR\x04make\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\x12\x12\n" +
	"\x04year\x18\x03 \x01(\x05R\x04year\x12\x1a\n" +
	"\bcategory\x18\x04 \x01(\tR\bcategory\x12\"\n" +
	"\rprice_per_day\x18\x05 \x01(\x01R\vpricePerDay\x12\x1a\n" +
	"\blocation\x18\x06 \x01(\tR\blocation\"\xc3\x01\n" +
	"\x10UpdateCarRequest\x12\x15\n" +
	"\x06car_id\x18\x01 \x01(\tR\x05carId\x12\x12\n" +
	"\x04make\x18\x02 \x01(\tR\x04make\x12\x14\n" +
	"\x05model\x18\x03 \x01(\tR\x05model\x12\x12\n" +
	"\x04year\x18\x04 \x01(\x05R\x04year\x12\x1a\n" +
	"\bcategory\x18\x05 \x01(\tR\bcategory\x12\"\n" +
	"\rprice_per_day\x18\x06 \x01(\x01R\vpricePerDay\x12\x1a\n" +
	"\blocation\x18\a \x01(\tR\blocation\"%\n" +
	"\fCarIDRequest\x12\x15\n" +
	"\x06car_id\x18\x01 \x01(\tR\x05carId\"D\n" +
	"\x0eDeleteResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xdc\x01\n" +
	"\vCarResponse\x12\x15\n" +
	"\x06car_id\x18\x01 \x01(\tR\x05carId\x12\x12\n" +
	"\x04make\x18\x02 \x01(\tR\x04make\x12\x14\n" +
	"\x05model\x18\x03 \x01(\tR\x05model\x12\x12\n" +
	"\x04year\x18\x04 \x01(\x05R\x04year\x12\x1a\n" +
	"\bcategory\x18\x05 \x01(\tR\bcategory\x12\"\n" +
	"\rprice_per_day\x18\x06 \x01(\x01R\vpricePerDay\x12\x1a\n" +
	"\blocation\x18\a \x01(\tR\blocation\x12\x1c\n" +
	"\tavailable\x18\b \x01(\bR\tavailable\"q\n" +
	"\rSearchRequest\x12\x1a\n" +
	"\blocation\x18\x01 \x01(\tR\blocation\x12\x1a\n" +
	"\bcategory\x18\x02 \x01(\tR\bcategory\x12\x12\n" +
	"\x04make\x18\x03 \x01(\tR\x04make\x12\x14\n" +
	"\x05model\x18\x04 \x01(\tR\x05model\"Q\n" +
	"\x0fCarListResponse\x12>\n" +
	"\x04cars\x18\x01 \x03(\v2*.carrental.com.proto.inventory.CarResponseR\x04cars\"f\n" +
	"\x13AvailabilityRequest\x12\x15\n" +
	"\x06car_id\x18\x01 \x01(\tR\x05carId\x12\x1d\n" +
	"\n" +
	"start_date\x18\x02 \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\x03 \x01(\tR\aendDate\"4\n" +
	"\x14AvailabilityResponse\x12\x1c\n" +
	"\tavailable\x18\x01 \x01(\bR\tavailable\"G\n" +
	"\x10CarStatusRequest\x12\x15\n" +
	"\x06car_id\x18\x01 \x01(\tR\x05carId\x12\x1c\n" +
	"\tavailable\x18\x02 \x01(\bR\tavailable\"+\n" +
	"\x10CarIDListRequest\x12\x17\n" +
	"\acar_ids\x18\x01 \x03(\tR\x06carIds2\x85\a\n" +
	"\x10InventoryService\x12b\n" +
	"\x06AddCar\x12,.carrental.com.proto.inventory.AddCarRequest\x1a*.carrental.com.proto.inventory.CarResponse\x12h\n" +
	"\tUpdateCar\x12/.carrental.com.proto.inventory.UpdateCarRequest\x1a*.carrental.com.proto.inventory.CarResponse\x12g\n" +
	"\tDeleteCar\x12+.carrental.com.proto.inventory.CarIDRequest\x1a-.carrental.com.proto.inventory.DeleteResponse\x12e\n" +
	"\n" +
	"GetCarByID\x12+.carrental.com.proto.inventory.CarIDRequest\x1a*.carrental.com.proto.inventory.CarResponse\x12s\n" +
	"\x13SearchAvailableCars\x12,.carrental.com.proto.inventory.SearchRequest\x1a..carrental.com.proto.inventory.CarListResponse\x12|\n" +
	"\x11CheckAvailability\x122.carrental.com.proto.inventory.AvailabilityRequest\x1a3.carrental.com.proto.inventory.AvailabilityResponse\x12n\n" +
	"\x0fUpdateCarStatus\x12/.carrental.com.proto.inventory.CarStatusRequest\x1a*.carrental.com.proto.inventory.CarResponse\x12p\n" +
	"\rListCarsByIDs\x12/.carrental.com.proto.inventory.CarIDListRequest\x1a..carrental.com.proto.inventory.CarListResponseB\x1fZ\x1dcarrental.com/proto/inventoryb\x06proto3"

var (
	file_inventory_inventory_proto_rawDescOnce sync.Once
	file_inventory_inventory_proto_rawDescData []byte
)

func file_inventory_inventory_proto_rawDescGZIP() []byte {
	file_inventory_inventory_proto_rawDescOnce.Do(func() {
		file_inventory_inventory_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_inventory_inventory_proto_rawDesc), len(file_inventory_inventory_proto_rawDesc)))
	})
	return file_inventory_inventory_proto_rawDescData
}

var file_inventory_inventory_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_inventory_inventory_proto_goTypes = []any{
	(*CreateProductRequest)(nil), // 0: carrental.com.proto.inventory.CreateProductRequest
	(*GetProductRequest)(nil),    // 1: carrental.com.proto.inventory.GetProductRequest
	(*UpdateProductRequest)(nil), // 2: carrental.com.proto.inventory.UpdateProductRequest
	(*DeleteProductRequest)(nil), // 3: carrental.com.proto.inventory.DeleteProductRequest
	(*ListProductsRequest)(nil),  // 4: carrental.com.proto.inventory.ListProductsRequest
	(*AdjustStockRequest)(nil),   // 5: carrental.com.proto.inventory.AdjustStockRequest
	(*ProductResponse)(nil),      // 6: carrental.com.proto.inventory.ProductResponse
	(*ListProductsResponse)(nil), // 7: carrental.com.proto.inventory.ListProductsResponse
	(*Empty)(nil),                // 8: carrental.com.proto.inventory.Empty
	(*AddCarRequest)(nil),        // 9: carrental.com.proto.inventory.AddCarRequest
	(*UpdateCarRequest)(nil),     // 10: carrental.com.proto.inventory.UpdateCarRequest
	(*CarIDRequest)(nil),         // 11: carrental.com.proto.inventory.CarIDRequest
	(*DeleteResponse)(nil),       // 12: carrental.com.proto.inventory.DeleteResponse
	(*CarResponse)(nil),          // 13: carrental.com.proto.inventory.CarResponse
	(*SearchRequest)(nil),        // 14: carrental.com.proto.inventory.SearchRequest
	(*CarListResponse)(nil),      // 15: carrental.com.proto.inventory.CarListResponse
	(*AvailabilityRequest)(nil),  // 16: carrental.com.proto.inventory.AvailabilityRequest
	(*AvailabilityResponse)(nil), // 17: carrental.com.proto.inventory.AvailabilityResponse
	(*CarStatusRequest)(nil),     // 18: carrental.com.proto.inventory.CarStatusRequest
	(*CarIDListRequest)(nil),     // 19: carrental.com.proto.inventory.CarIDListRequest
}
var file_inventory_inventory_proto_depIdxs = []int32{
	6,  // 0: carrental.com.proto.inventory.ListProductsResponse.products:type_name -> carrental.com.proto.inventory.ProductResponse
	13, // 1: carrental.com.proto.inventory.CarListResponse.cars:type_name -> carrental.com.proto.inventory.CarResponse
	9,  // 2: carrental.com.proto.inventory.InventoryService.AddCar:input_type -> carrental.com.proto.inventory.AddCarRequest
	10, // 3: carrental.com.proto.inventory.InventoryService.UpdateCar:input_type -> carrental.com.proto.inventory.UpdateCarRequest
	11, // 4: carrental.com.proto.inventory.InventoryService.DeleteCar:input_type -> carrental.com.proto.inventory.CarIDRequest
	11, // 5: carrental.com.proto.inventory.InventoryService.GetCarByID:input_type -> carrental.com.proto.inventory.CarIDRequest
	14, // 6: carrental.com.proto.inventory.InventoryService.SearchAvailableCars:input_type -> carrental.com.proto.inventory.SearchRequest
	16, // 7: carrental.com.proto.inventory.InventoryService.CheckAvailability:input_type -> carrental.com.proto.inventory.AvailabilityRequest
	18, // 8: carrental.com.proto.inventory.InventoryService.UpdateCarStatus:input_type -> carrental.com.proto.inventory.CarStatusRequest
	19, // 9: carrental.com.proto.inventory.InventoryService.ListCarsByIDs:input_type -> carrental.com.proto.inventory.CarIDListRequest
	13, // 10: carrental.com.proto.inventory.InventoryService.AddCar:output_type -> carrental.com.proto.inventory.CarResponse
	13, // 11: carrental.com.proto.inventory.InventoryService.UpdateCar:output_type -> carrental.com.proto.inventory.CarResponse
	12, // 12: carrental.com.proto.inventory.InventoryService.DeleteCar:output_type -> carrental.com.proto.inventory.DeleteResponse
	13, // 13: carrental.com.proto.inventory.InventoryService.GetCarByID:output_type -> carrental.com.proto.inventory.CarResponse
	15, // 14: carrental.com.proto.inventory.InventoryService.SearchAvailableCars:output_type -> carrental.com.proto.inventory.CarListResponse
	17, // 15: carrental.com.proto.inventory.InventoryService.CheckAvailability:output_type -> carrental.com.proto.inventory.AvailabilityResponse
	13, // 16: carrental.com.proto.inventory.InventoryService.UpdateCarStatus:output_type -> carrental.com.proto.inventory.CarResponse
	15, // 17: carrental.com.proto.inventory.InventoryService.ListCarsByIDs:output_type -> carrental.com.proto.inventory.CarListResponse
	10, // [10:18] is the sub-list for method output_type
	2,  // [2:10] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_inventory_inventory_proto_init() }
func file_inventory_inventory_proto_init() {
	if File_inventory_inventory_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_inventory_inventory_proto_rawDesc), len(file_inventory_inventory_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_inventory_inventory_proto_goTypes,
		DependencyIndexes: file_inventory_inventory_proto_depIdxs,
		MessageInfos:      file_inventory_inventory_proto_msgTypes,
	}.Build()
	File_inventory_inventory_proto = out.File
	file_inventory_inventory_proto_goTypes = nil
	file_inventory_inventory_proto_depIdxs = nil
}
